# Generated by Django 4.2.5 on 2024-02-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_agreement', models.CharField(max_length=255)),
                ('tax_for_ad', models.CharField(default=None, max_length=255)),
                ('date_end', models.DateField()),
            ],
        ),
    ]
