# Generated by Django 4.2.5 on 2024-01-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adding_new_tenant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
