# Generated by Django 4.2.5 on 2024-02-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adding_new_tenant', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=255)),
                ('number_of_contract', models.CharField(max_length=255)),
                ('date_beginning', models.DateField()),
                ('date_end', models.DateField()),
                ('date_of_agreement', models.DateField()),
                ('landlord', models.CharField(max_length=255)),
                ('tenant', models.CharField(max_length=255)),
                ('tenant_ps', models.CharField(max_length=255)),
                ('type_of_contract', models.CharField(max_length=255)),
                ('tax_for_ad', models.CharField(max_length=255)),
                ('in_work', models.CharField(max_length=255)),
                ('closed', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('number_of_agreement', models.CharField(max_length=255)),
                ('main_agreement', models.CharField(max_length=255)),
                ('lot', models.CharField(max_length=255)),
            ],
        ),
    ]
